name: CI

on:
  push:
    branches: [main]
    paths:
      - '**.go'
      - 'go.mod'
  pull_request:
    branches: [main]
    paths:
      - '**.go'
      - 'go.mod'

permissions:
  contents: read
  pull-requests: read

jobs:
  test:
    strategy:
      matrix:
        go-version: ["current", "stable"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
      - uses: actions/setup-go@v6
        if: matrix.go-version == 'current'
        with:
          go-version-file: go.mod
          cache: false
      - uses: actions/setup-go@v6
        if: matrix.go-version != 'current'
        with:
          go-version: ${{ matrix.go-version }}
          cache: false
      - run: |
          go mod tidy
          git diff --exit-code go.mod
      - run: go test ./... -v -race -count=1

  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: stable
          cache: false
      - uses: golangci/golangci-lint-action@v9
        with:
          version: latest
